security:
    always_authenticate_before_granting:  true
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN_A:         ROLE_USER
        ROLE_ADMIN_G:       ROLE_USER_G
        ROLE_ADMIN_E:       ROLE_USER_E
        ROLE_ADMIN_V:       ROLE_USER_V
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ADMIN_A, ROLE_ADMIN_G,ROLE_ADMIN_V,ROLE_ADMIN_E]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                # csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                csrf_provider: form.csrf_provider

            logout:
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/article, role: ROLE_ADMIN_A }
        - { path: ^/backend/event, role: ROLE_ADMIN_E }
        - { path: ^/backend/venue, role: ROLE_ADMIN_V }
        - { path: ^/backend/gallery, role: ROLE_ADMIN_G }
        - { path: ^/backend/user, role: ROLE_SUPER_ADMIN }
        - { path: ^/backend, role: [ROLE_USER, ROLE_USER_G, ROLE_USER_E, ROLE_USER_V, ROLE_SUPER_ADMIN ] }
